### ISSUE TITLE
Transactions don't support coroutines

### ISSUE THREAD

**Issue by asm0dey** [angryziber/kotlin-jooby-svelte-template#4]
Given jooby is all about coroutines Transaction should be not Thread-bound, but CoroutineContext-bound because we can never be sure that it's called from different threads. Connections should be coroutine-bound too. In current implementation it's theoretically possible to for several coroutines to pass their statements into single transactions which can break everything :)

**Comment by angryziber** [comment]
Jooby doesn't support/use coroutines by default. You need to wrap routes in `coroutine {}` and declare them with `suspend` modifier for that.

Because my app mostly uses JDBC as a backend - coroutines will not add any value, only complicate things and require declare everything with `suspend` keyword. I have actually tried that and `suspend` everythere without much benefit didn't feel right.

**Comment by asm0dey** [comment]
Agreed

**Comment by angryziber** [comment]
@asm0dey finally I got a chance to use coroutines with Jooby, but I realized that it is very hard to add Transaction or MDC/logging context to coroutine scope in Jooby.

See the issue for details: https://github.com/jooby-project/jooby/issues/2257

Do you know a solution?
